services:
  - type: web
    name: app-production-planning
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get install -y glpk-utils || true
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
